name: Performance and Security Scanning

on: [push, pull_request]

env:
  TARGET_URL: https://juice-shop.herokuapp.com/
  JMETER_VERSION: 5.6.3
  ZAP_VERSION: 2.12.0

jobs:
  performance-security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Configurar credenciales de AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # Instalar Java (requisito para JMeter)
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install JMeter
      run: |
        wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
        tar -xzvf apache-jmeter-${{ env.JMETER_VERSION }}.tgz
        echo "$PWD/apache-jmeter-${{ env.JMETER_VERSION }}/bin" >> $GITHUB_PATH
    
    - name: Create JMeter Test Plan
      run: |
        cat > performance-test.jmx << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
          <hashTree>
            <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Performance Test" enabled="true">
              <stringProp name="TestPlan.comments"></stringProp>
              <boolProp name="TestPlan.functional_mode">false</boolProp>
              <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
              <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
              <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                <collectionProp name="Arguments.elements"/>
              </elementProp>
              <stringProp name="TestPlan.user_define_classpath"></stringProp>
            </TestPlan>
            <hashTree>
              <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Load Test" enabled="true">
                <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
                  <boolProp name="LoopController.continue_forever">false</boolProp>
                  <intProp name="LoopController.loops">-1</intProp>
                </elementProp>
                <stringProp name="ThreadGroup.num_threads">20</stringProp>
                <stringProp name="ThreadGroup.ramp_time">1</stringProp>
                <boolProp name="ThreadGroup.scheduler">true</boolProp>
                <stringProp name="ThreadGroup.duration">60</stringProp>
                <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
              </ThreadGroup>
              <hashTree>
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
                  <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                    <collectionProp name="Arguments.elements"/>
                  </elementProp>
                  <stringProp name="HTTPSampler.domain">juice-shop.herokuapp.com</stringProp>
                  <stringProp name="HTTPSampler.port"></stringProp>
                  <stringProp name="HTTPSampler.protocol">https</stringProp>
                  <stringProp name="HTTPSampler.contentEncoding"></stringProp>
                  <stringProp name="HTTPSampler.path">/</stringProp>
                  <stringProp name="HTTPSampler.method">GET</stringProp>
                  <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                  <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
                  <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                  <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
                  <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
                  <stringProp name="HTTPSampler.connect_timeout"></stringProp>
                  <stringProp name="HTTPSampler.response_timeout"></stringProp>
                </HTTPSamplerProxy>
                <hashTree/>
                
                <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="View Results Tree" enabled="true">
                  <boolProp name="ResultCollector.error_logging">false</boolProp>
                  <objProp>
                    <name>saveConfig</name>
                    <value class="SampleSaveConfiguration">
                      <time>true</time>
                      <latency>true</latency>
                      <timestamp>true</timestamp>
                      <success>true</success>
                      <label>true</label>
                      <code>true</code>
                      <message>true</message>
                      <threadName>true</threadName>
                      <dataType>true</dataType>
                      <encoding>false</encoding>
                      <assertions>true</assertions>
                      <subresults>true</subresults>
                      <responseData>false</responseData>
                      <samplerData>false</samplerData>
                      <xml>false</xml>
                      <fieldNames>true</fieldNames>
                      <responseHeaders>false</responseHeaders>
                      <requestHeaders>false</requestHeaders>
                      <responseDataOnError>false</responseDataOnError>
                      <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
                      <assertionsResultsToSave>0</assertionsResultsToSave>
                      <bytes>true</bytes>
                      <sentBytes>true</sentBytes>
                      <url>true</url>
                      <threadCounts>true</threadCounts>
                      <idleTime>true</idleTime>
                      <connectTime>true</connectTime>
                    </value>
                  </objProp>
                  <stringProp name="filename"></stringProp>
                </ResultCollector>
                <hashTree/>
              </hashTree>
            </hashTree>
          </hashTree>
        </jmeterTestPlan>
        EOL
    
    - name: Run JMeter Performance Tests
      run: |
        jmeter -n -t performance-test.jmx -l performance-results.jtl -f -o jmeter-report
        
        if [ ! -d "jmeter-report" ]; then
          echo "::error::No se generó el directorio de informes de JMeter"
          pwd
          ls -la
          
          mkdir -p jmeter-report
          cp performance-results.jtl jmeter-report/
          
          echo '{"error": "Informe de JMeter no generado correctamente"}' > jmeter-report/statistics.json
        fi
          sudo apt-get update
          sudo apt-get install -y jq
          
          if [ -f "jmeter-report/statistics.json" ]; then
            cat jmeter-report/statistics.json | jq '.' > jmeter-performance-report.json
          else
            echo '{"error": "No se pudo generar informe de rendimiento"}' > jmeter-performance-report.json
          fi
          
    - name: Install OWASP ZAP
      run: |
        # Array de versiones a intentar
        VERSIONS=("2.14.0" "2.13.0" "2.12.0")
        
        for VERSION in "${VERSIONS[@]}"; do
          # Intentar descargar
          wget -q "https://github.com/zaproxy/zaproxy/releases/download/v${VERSION}/ZAP_${VERSION}_Linux.tar.gz" -O zap.tar.gz
          
          # Verificar descarga
          if [ $? -eq 0 ]; then
            echo "Descargando ZAP versión ${VERSION}"
            tar -xzf zap.tar.gz
            
            # Encontrar directorio de ZAP
            ZAP_DIR=$(find . -type d -name "ZAP_*" | head -n 1)
            
            if [ -n "$ZAP_DIR" ]; then
              echo "ZAP instalado desde versión ${VERSION}"
              # Agregar permisos de ejecución
              chmod +x "$ZAP_DIR/zap.sh"
              break
            fi
          fi
        done
        
        # Verificar si se instaló ZAP
        if [ ! -d "$ZAP_DIR" ]; then
          echo "No se pudo instalar OWASP ZAP"
          exit 1
        fi
        
        # Exportar la ruta completa de ZAP para usar en pasos posteriores
        echo "ZAP_FULL_PATH=$ZAP_DIR/zap.sh" >> $GITHUB_ENV
    
    - name: Run OWASP ZAP Security Scan
      run: |
        # Crear directorio temporal para informes
        mkdir -p ${{ github.workspace }}/zap-reports
    
        # Imprimir información de depuración
        echo "Escaneando URL: ${{ env.TARGET_URL }}"
        
        # Verificar que el script de ZAP existe
        if [ ! -f "./ZAP_2.14.0/zap.sh" ]; then
          echo "Error: No se encontró el script de ZAP"
          exit 1
        fi
        
        # Intentar escaneo básico
        "./ZAP_2.14.0/zap.sh" -cmd \
          -quickurl "${{ env.TARGET_URL }}" \
          -quickout "${{ github.workspace }}/zap-reports/zap-security-report.json" \
          -quickprogress \
          -silent \
        
        # Verificar si se generó el informe
        if [ ! -f "${{ github.workspace }}/zap-reports/zap-security-report.json" ]; then
          echo "Error: No se generó informe de seguridad"
          
          # Intentar escaneo alternativo
          "./ZAP_2.14.0/zap.sh" -cmd \
            -port 8080 \
            -host 0.0.0.0 \
            -config api.disablekey=true \
            -quickurl "${{ env.TARGET_URL }}" \
            -quickout "${{ github.workspace }}/zap-reports/zap-security-report-alt.json"
        fi
        
        - name: Upload Reports to S3
          run: |
            # Crear directorios de respaldo si no existen
            mkdir -p jmeter-report
            
            # Subir informe de rendimiento
            aws s3 cp jmeter-performance-report.json s3://${{ secrets.S3_BUCKET_NAME }}/informes/jmeter-report-${{ github.sha }}.json
            
            # Subir resultados de pruebas
            aws s3 cp performance-results.jtl s3://${{ secrets.S3_BUCKET_NAME }}/informes/jmeter-results-${{ github.sha }}.jtl
            
            # Intentar sincronizar, si falla copiar contenido manualmente
            aws s3 sync jmeter-report s3://${{ secrets.S3_BUCKET_NAME }}/informes/jmeter-report-${{ github.sha }}/ || {
              # Si sync falla, copiar archivos individuales
              for file in jmeter-report/*; do
                if [ -f "$file" ]; then
                  aws s3 cp "$file" "s3://${{ secrets.S3_BUCKET_NAME }}/informes/jmeter-report-${{ github.sha }}/$(basename "$file")"
                fi
              done
            }
